[2023-07-31T16:44:42.095-0500] {processor.py:157} INFO - Started process (PID=68771) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:44:42.097-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:44:42.098-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:44:42.097-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:44:42.102-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:44:42.101-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:44:42.103-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:44:42.102-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:44:42.103-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:44:42.115-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-31T16:45:29.702-0500] {processor.py:157} INFO - Started process (PID=68838) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:45:29.710-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:45:29.711-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:45:29.710-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:45:29.715-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:45:29.714-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:45:29.715-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:45:29.715-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:45:29.716-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:45:29.726-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-07-31T16:46:25.759-0500] {processor.py:157} INFO - Started process (PID=68914) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:46:25.766-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:46:25.767-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:46:25.767-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:46:25.771-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:46:25.770-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:46:25.772-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:46:25.772-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:46:25.772-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:46:25.783-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-31T16:47:18.239-0500] {processor.py:157} INFO - Started process (PID=68980) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:47:18.247-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:47:18.248-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:47:18.248-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:47:18.253-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:47:18.251-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:47:18.253-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:47:18.253-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:47:18.253-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:47:18.265-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-07-31T16:48:12.565-0500] {processor.py:157} INFO - Started process (PID=69046) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:48:12.574-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:48:12.576-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:48:12.575-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:48:12.584-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:48:12.582-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:48:12.585-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:48:12.585-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:48:12.585-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:48:12.601-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-07-31T16:49:04.013-0500] {processor.py:157} INFO - Started process (PID=69116) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:49:04.021-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:49:04.022-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:49:04.022-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:49:04.027-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:49:04.026-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:49:04.027-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:49:04.027-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:49:04.027-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:49:04.039-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-07-31T16:50:02.468-0500] {processor.py:157} INFO - Started process (PID=69200) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:02.476-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:50:02.477-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:02.476-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:02.483-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:02.481-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:50:02.483-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:02.483-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:50:02.484-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:02.497-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-31T16:50:59.518-0500] {processor.py:157} INFO - Started process (PID=69281) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:59.526-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:50:59.528-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:59.527-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:59.536-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:59.534-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:50:59.536-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:50:59.536-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:50:59.536-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:50:59.551-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-07-31T16:51:57.006-0500] {processor.py:157} INFO - Started process (PID=69353) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:51:57.014-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:51:57.016-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:51:57.015-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:51:57.021-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:51:57.020-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:51:57.022-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:51:57.022-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:51:57.022-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:51:57.033-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-07-31T16:52:54.509-0500] {processor.py:157} INFO - Started process (PID=69441) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:52:54.519-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:52:54.522-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:52:54.521-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:52:54.533-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:52:54.530-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:52:54.534-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:52:54.533-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:52:54.534-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:52:54.552-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2023-07-31T16:53:48.006-0500] {processor.py:157} INFO - Started process (PID=69498) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:53:48.015-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:53:48.016-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:53:48.016-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:53:48.022-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:53:48.020-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:53:48.022-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:53:48.022-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:53:48.023-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:53:48.037-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-31T16:54:36.503-0500] {processor.py:157} INFO - Started process (PID=69559) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:54:36.511-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:54:36.514-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:54:36.513-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:54:36.525-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:54:36.522-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:54:36.526-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:54:36.525-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:54:36.526-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:54:36.544-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-31T16:55:31.701-0500] {processor.py:157} INFO - Started process (PID=69636) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:55:31.714-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:55:31.716-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:55:31.715-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:55:31.720-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:55:31.719-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:55:31.720-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:55:31.720-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:55:31.721-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:55:31.733-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-07-31T16:56:24.093-0500] {processor.py:157} INFO - Started process (PID=69699) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:56:24.101-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-31T16:56:24.102-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:56:24.102-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:56:24.108-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:56:24.107-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-31T16:56:24.109-0500] {logging_mixin.py:150} INFO - [2023-07-31T16:56:24.108-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-31T16:56:24.109-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-31T16:56:24.119-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
