[2023-08-01T20:25:40.596-0500] {processor.py:157} INFO - Started process (PID=99554) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:25:40.597-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-01T20:25:40.598-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:25:40.597-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:25:40.604-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:25:40.602-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-01T20:25:40.604-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:25:40.604-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-01T20:25:40.605-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:25:40.618-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-08-01T20:26:31.412-0500] {processor.py:157} INFO - Started process (PID=99698) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:26:31.421-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-01T20:26:31.423-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:26:31.422-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:26:31.431-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:26:31.429-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-01T20:26:31.432-0500] {logging_mixin.py:150} INFO - [2023-08-01T20:26:31.432-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-01T20:26:31.433-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-01T20:26:31.444-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-08-02T11:08:47.197-0500] {processor.py:157} INFO - Started process (PID=105246) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:08:47.206-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:08:47.208-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:08:47.207-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:08:47.217-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:08:47.214-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:08:47.217-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:08:47.217-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:08:47.218-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:08:47.236-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-08-02T11:09:41.322-0500] {processor.py:157} INFO - Started process (PID=105356) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:09:41.331-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:09:41.335-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:09:41.334-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:09:41.347-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:09:41.344-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:09:41.347-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:09:41.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:09:41.348-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:09:41.362-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2023-08-02T11:10:34.263-0500] {processor.py:157} INFO - Started process (PID=105554) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:10:34.270-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:10:34.271-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:10:34.271-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:10:34.275-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:10:34.274-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:10:34.276-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:10:34.276-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:10:34.276-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:10:34.289-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-02T11:11:45.732-0500] {processor.py:157} INFO - Started process (PID=105745) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:11:45.735-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:11:45.737-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:11:45.736-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:11:45.743-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:11:45.741-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:11:45.744-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:11:45.744-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:11:45.745-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:11:45.766-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-08-02T11:12:35.367-0500] {processor.py:157} INFO - Started process (PID=105864) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:12:35.375-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:12:35.376-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:12:35.375-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:12:35.379-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:12:35.378-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:12:35.380-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:12:35.380-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:12:35.380-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:12:35.391-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-08-02T11:13:37.007-0500] {processor.py:157} INFO - Started process (PID=105987) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:13:37.015-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:13:37.016-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:13:37.016-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:13:37.021-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:13:37.019-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:13:37.022-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:13:37.021-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:13:37.022-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:13:37.034-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-08-02T11:14:40.950-0500] {processor.py:157} INFO - Started process (PID=106067) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:14:40.958-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:14:40.959-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:14:40.958-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:14:40.963-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:14:40.962-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:14:40.963-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:14:40.963-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:14:40.963-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:14:40.975-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-08-02T11:15:53.484-0500] {processor.py:157} INFO - Started process (PID=106297) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:15:53.493-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:15:53.495-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:15:53.494-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:15:53.508-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:15:53.504-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:15:53.508-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:15:53.508-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:15:53.509-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:15:53.523-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-08-02T11:17:02.984-0500] {processor.py:157} INFO - Started process (PID=106478) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:17:02.994-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:17:02.996-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:17:02.995-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:17:03.007-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:17:03.005-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:17:03.008-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:17:03.008-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:17:03.009-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:17:03.023-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-08-02T11:18:08.964-0500] {processor.py:157} INFO - Started process (PID=106678) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:18:08.974-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:18:08.978-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:18:08.976-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:18:08.990-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:18:08.987-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:18:08.990-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:18:08.990-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:18:08.991-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:18:09.008-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2023-08-02T11:19:16.387-0500] {processor.py:157} INFO - Started process (PID=106841) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:19:16.395-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:19:16.396-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:19:16.396-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:19:16.401-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:19:16.400-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:19:16.401-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:19:16.401-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:19:16.402-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:19:16.414-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-08-02T11:20:05.062-0500] {processor.py:157} INFO - Started process (PID=106931) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:05.069-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:20:05.070-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:05.070-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:05.074-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:05.073-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:20:05.075-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:05.074-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:20:05.075-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:05.087-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-08-02T11:20:57.098-0500] {processor.py:157} INFO - Started process (PID=107087) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:57.105-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:20:57.106-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:57.106-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:57.114-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:57.111-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:20:57.114-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:20:57.114-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:20:57.115-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:20:57.132-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-08-02T11:22:01.550-0500] {processor.py:157} INFO - Started process (PID=107376) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:22:01.558-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:22:01.560-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:22:01.559-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:22:01.567-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:22:01.565-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:22:01.567-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:22:01.567-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:22:01.567-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:22:01.585-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2023-08-02T11:23:13.020-0500] {processor.py:157} INFO - Started process (PID=107893) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:23:13.035-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:23:13.036-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:23:13.036-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:23:13.127-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:23:13.126-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:23:13.128-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:23:13.127-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:23:13.128-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:23:13.325-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.420 seconds
[2023-08-02T11:24:44.749-0500] {processor.py:157} INFO - Started process (PID=108303) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:24:44.758-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:24:44.761-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:24:44.760-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:24:44.775-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:24:44.771-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:24:44.776-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:24:44.775-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:24:44.777-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:24:44.804-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2023-08-02T11:25:53.993-0500] {processor.py:157} INFO - Started process (PID=108425) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:25:54.004-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-02T11:25:54.007-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:25:54.006-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:25:54.020-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:25:54.016-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-02T11:25:54.021-0500] {logging_mixin.py:150} INFO - [2023-08-02T11:25:54.021-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-02T11:25:54.022-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-02T11:25:54.045-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
