[2023-07-28T19:00:06.381-0500] {processor.py:157} INFO - Started process (PID=59800) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:06.382-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:00:06.384-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:06.383-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:06.389-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:06.388-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:00:06.390-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:06.390-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:00:06.390-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:06.404-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2023-07-28T19:00:58.723-0500] {processor.py:157} INFO - Started process (PID=59859) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:58.731-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:00:58.732-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:58.732-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:58.738-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:58.737-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:00:58.738-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:00:58.738-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:00:58.739-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:00:58.753-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T19:01:53.613-0500] {processor.py:157} INFO - Started process (PID=59922) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:01:53.621-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:01:53.623-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:01:53.622-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:01:53.631-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:01:53.629-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:01:53.631-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:01:53.631-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:01:53.632-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:01:53.648-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:02:44.203-0500] {processor.py:157} INFO - Started process (PID=59981) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:02:44.212-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:02:44.215-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:02:44.213-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:02:44.226-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:02:44.223-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:02:44.227-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:02:44.227-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:02:44.227-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:02:44.244-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:03:38.806-0500] {processor.py:157} INFO - Started process (PID=60041) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:03:38.814-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:03:38.817-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:03:38.816-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:03:38.828-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:03:38.825-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:03:38.829-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:03:38.829-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:03:38.830-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:03:38.847-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:04:36.312-0500] {processor.py:157} INFO - Started process (PID=60105) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:04:36.321-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:04:36.324-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:04:36.322-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:04:36.335-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:04:36.332-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:04:36.336-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:04:36.336-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:04:36.337-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:04:36.353-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-28T19:05:33.179-0500] {processor.py:157} INFO - Started process (PID=60171) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:05:33.192-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:05:33.193-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:05:33.193-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:05:33.198-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:05:33.197-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:05:33.199-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:05:33.199-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:05:33.199-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:05:33.213-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T19:06:26.358-0500] {processor.py:157} INFO - Started process (PID=60231) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:06:26.366-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:06:26.368-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:06:26.367-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:06:26.374-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:06:26.372-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:06:26.374-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:06:26.374-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:06:26.374-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:06:26.389-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T19:07:19.501-0500] {processor.py:157} INFO - Started process (PID=60292) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:07:19.508-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:07:19.509-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:07:19.508-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:07:19.512-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:07:19.511-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:07:19.512-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:07:19.512-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:07:19.513-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:07:19.522-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T19:08:11.126-0500] {processor.py:157} INFO - Started process (PID=60351) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:08:11.134-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:08:11.135-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:08:11.135-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:08:11.141-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:08:11.140-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:08:11.142-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:08:11.141-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:08:11.142-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:08:11.157-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-07-28T19:09:03.663-0500] {processor.py:157} INFO - Started process (PID=60410) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:03.672-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:09:03.674-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:03.673-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:03.686-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:03.683-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:09:03.687-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:03.687-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:09:03.688-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:03.705-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-28T19:09:58.630-0500] {processor.py:157} INFO - Started process (PID=60479) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:58.637-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:09:58.638-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:58.638-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:58.642-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:58.641-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:09:58.643-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:09:58.642-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:09:58.643-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:09:58.653-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-28T19:10:54.232-0500] {processor.py:157} INFO - Started process (PID=60542) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:10:54.239-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:10:54.240-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:10:54.240-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:10:54.244-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:10:54.243-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:10:54.244-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:10:54.244-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:10:54.244-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:10:54.253-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T19:11:45.799-0500] {processor.py:157} INFO - Started process (PID=60601) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:11:45.807-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:11:45.810-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:11:45.809-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:11:45.821-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:11:45.818-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:11:45.822-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:11:45.821-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:11:45.822-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:11:45.836-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:12:40.904-0500] {processor.py:157} INFO - Started process (PID=60663) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:12:40.912-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:12:40.914-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:12:40.913-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:12:40.921-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:12:40.919-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:12:40.921-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:12:40.921-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:12:40.921-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:12:40.932-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-07-28T19:13:38.613-0500] {processor.py:157} INFO - Started process (PID=60732) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:13:38.621-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:13:38.622-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:13:38.621-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:13:38.625-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:13:38.624-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:13:38.626-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:13:38.625-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:13:38.626-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:13:38.637-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-28T19:14:32.357-0500] {processor.py:157} INFO - Started process (PID=60793) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:14:32.365-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:14:32.366-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:14:32.366-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:14:32.372-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:14:32.371-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:14:32.373-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:14:32.373-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:14:32.373-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:14:32.387-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-07-28T19:15:22.051-0500] {processor.py:157} INFO - Started process (PID=60863) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:15:22.059-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:15:22.061-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:15:22.061-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:15:22.069-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:15:22.067-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:15:22.070-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:15:22.069-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:15:22.070-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:15:22.084-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:16:22.811-0500] {processor.py:157} INFO - Started process (PID=60930) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:16:22.818-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:16:22.819-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:16:22.819-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:16:22.823-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:16:22.822-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:16:22.823-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:16:22.823-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:16:22.823-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:16:22.833-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-28T19:17:11.979-0500] {processor.py:157} INFO - Started process (PID=60992) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:17:11.987-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:17:11.989-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:17:11.988-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:17:11.997-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:17:11.995-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:17:11.997-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:17:11.997-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:17:11.998-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:17:12.013-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:18:05.675-0500] {processor.py:157} INFO - Started process (PID=61051) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:18:05.688-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:18:05.690-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:18:05.689-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:18:05.696-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:18:05.694-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:18:05.696-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:18:05.696-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:18:05.696-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:18:05.711-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:19:01.409-0500] {processor.py:157} INFO - Started process (PID=61112) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:01.418-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:19:01.421-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:01.420-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:01.432-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:01.429-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:19:01.433-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:01.433-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:19:01.434-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:01.450-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:19:55.220-0500] {processor.py:157} INFO - Started process (PID=61176) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:55.228-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:19:55.230-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:55.230-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:55.237-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:55.235-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:19:55.237-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:19:55.237-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:19:55.238-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:19:55.250-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T19:20:53.327-0500] {processor.py:157} INFO - Started process (PID=61240) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:20:53.336-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:20:53.339-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:20:53.338-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:20:53.350-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:20:53.347-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:20:53.351-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:20:53.351-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:20:53.352-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:20:53.369-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-28T19:21:43.832-0500] {processor.py:157} INFO - Started process (PID=61300) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:21:43.841-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:21:43.843-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:21:43.842-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:21:43.850-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:21:43.848-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:21:43.851-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:21:43.851-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:21:43.851-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:21:43.867-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:22:37.138-0500] {processor.py:157} INFO - Started process (PID=61361) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:22:37.146-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:22:37.148-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:22:37.147-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:22:37.154-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:22:37.152-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:22:37.154-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:22:37.154-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:22:37.154-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:22:37.168-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T19:23:27.614-0500] {processor.py:157} INFO - Started process (PID=61418) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:23:27.622-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:23:27.624-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:23:27.624-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:23:27.631-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:23:27.629-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:23:27.631-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:23:27.631-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:23:27.632-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:23:27.643-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-07-28T19:24:21.495-0500] {processor.py:157} INFO - Started process (PID=61478) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:24:21.504-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:24:21.505-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:24:21.505-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:24:21.513-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:24:21.511-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:24:21.514-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:24:21.514-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:24:21.514-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:24:21.531-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-07-28T19:25:16.401-0500] {processor.py:157} INFO - Started process (PID=61542) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:25:16.410-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:25:16.412-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:25:16.411-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:25:16.424-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:25:16.420-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:25:16.424-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:25:16.424-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:25:16.425-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:25:16.442-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:26:15.713-0500] {processor.py:157} INFO - Started process (PID=61614) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:26:15.721-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:26:15.722-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:26:15.721-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:26:15.726-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:26:15.725-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:26:15.727-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:26:15.726-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:26:15.727-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:26:15.738-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-07-28T19:27:07.706-0500] {processor.py:157} INFO - Started process (PID=61674) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:27:07.715-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:27:07.716-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:27:07.716-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:27:07.723-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:27:07.721-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:27:07.723-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:27:07.723-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:27:07.724-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:27:07.735-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-07-28T19:28:02.477-0500] {processor.py:157} INFO - Started process (PID=61736) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:02.485-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:28:02.488-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:02.487-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:02.500-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:02.497-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:28:02.501-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:02.500-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:28:02.501-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:02.518-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-07-28T19:28:58.831-0500] {processor.py:157} INFO - Started process (PID=61799) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:58.839-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:28:58.840-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:58.840-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:58.845-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:58.843-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:28:58.845-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:28:58.845-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:28:58.845-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:28:58.857-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-07-28T19:29:55.349-0500] {processor.py:157} INFO - Started process (PID=61867) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:29:55.358-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:29:55.360-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:29:55.359-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:29:55.372-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:29:55.369-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:29:55.373-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:29:55.372-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:29:55.373-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:29:55.390-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T19:30:50.204-0500] {processor.py:157} INFO - Started process (PID=61929) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:30:50.214-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:30:50.215-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:30:50.215-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:30:50.219-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:30:50.218-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:30:50.219-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:30:50.219-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:30:50.219-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:30:50.228-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-07-28T19:31:42.264-0500] {processor.py:157} INFO - Started process (PID=61990) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:31:42.271-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:31:42.272-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:31:42.272-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:31:42.276-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:31:42.275-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:31:42.276-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:31:42.276-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:31:42.277-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:31:42.287-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T19:32:30.186-0500] {processor.py:157} INFO - Started process (PID=62046) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:32:30.195-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:32:30.198-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:32:30.197-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:32:30.210-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:32:30.207-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:32:30.210-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:32:30.210-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:32:30.211-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:32:30.225-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T19:33:28.252-0500] {processor.py:157} INFO - Started process (PID=62937) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:33:28.259-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:33:28.260-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:33:28.260-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:33:28.264-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:33:28.262-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:33:28.264-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:33:28.264-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:33:28.264-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:33:28.273-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T19:34:24.062-0500] {processor.py:157} INFO - Started process (PID=63000) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:34:24.070-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:34:24.072-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:34:24.071-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:34:24.077-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:34:24.076-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:34:24.078-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:34:24.077-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:34:24.078-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:34:24.092-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T19:35:19.468-0500] {processor.py:157} INFO - Started process (PID=63065) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:35:19.475-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:35:19.476-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:35:19.476-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:35:19.480-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:35:19.479-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:35:19.480-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:35:19.480-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:35:19.480-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:35:19.489-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T19:36:18.975-0500] {processor.py:157} INFO - Started process (PID=63130) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:36:18.983-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:36:18.986-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:36:18.985-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:36:18.997-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:36:18.994-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:36:18.998-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:36:18.998-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:36:18.999-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:36:19.017-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-07-28T19:37:09.237-0500] {processor.py:157} INFO - Started process (PID=63187) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:37:09.245-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:37:09.247-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:37:09.246-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:37:09.255-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:37:09.253-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:37:09.255-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:37:09.255-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:37:09.256-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:37:09.272-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-07-28T19:38:05.918-0500] {processor.py:157} INFO - Started process (PID=63251) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:05.931-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:38:05.934-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:05.933-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:05.945-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:05.942-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:38:05.946-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:05.946-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:38:05.947-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:05.966-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-07-28T19:38:59.849-0500] {processor.py:157} INFO - Started process (PID=63313) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:59.857-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:38:59.859-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:59.859-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:59.865-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:59.864-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:38:59.866-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:38:59.866-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:38:59.866-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:38:59.882-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-07-28T19:39:51.849-0500] {processor.py:157} INFO - Started process (PID=63371) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:39:51.857-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:39:51.858-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:39:51.858-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:39:51.864-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:39:51.863-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:39:51.865-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:39:51.865-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:39:51.865-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:39:51.880-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-07-28T19:40:49.837-0500] {processor.py:157} INFO - Started process (PID=63433) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:40:49.846-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:40:49.849-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:40:49.848-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:40:49.860-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:40:49.857-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:40:49.861-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:40:49.860-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:40:49.861-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:40:49.877-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2023-07-28T19:41:46.870-0500] {processor.py:157} INFO - Started process (PID=63496) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:41:46.876-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:41:46.877-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:41:46.876-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:41:46.881-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:41:46.880-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:41:46.881-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:41:46.881-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:41:46.881-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:41:46.891-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T19:42:44.432-0500] {processor.py:157} INFO - Started process (PID=63560) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:42:44.440-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:42:44.443-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:42:44.442-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:42:44.455-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:42:44.452-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:42:44.456-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:42:44.455-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:42:44.456-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:42:44.475-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:43:39.012-0500] {processor.py:157} INFO - Started process (PID=63622) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:43:39.020-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:43:39.021-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:43:39.021-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:43:39.027-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:43:39.025-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:43:39.027-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:43:39.027-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:43:39.028-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:43:39.042-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T19:44:34.077-0500] {processor.py:157} INFO - Started process (PID=63682) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:44:34.086-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:44:34.089-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:44:34.088-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:44:34.100-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:44:34.097-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:44:34.101-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:44:34.101-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:44:34.101-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:44:34.116-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-07-28T19:45:29.532-0500] {processor.py:157} INFO - Started process (PID=63748) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:45:29.546-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:45:29.547-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:45:29.547-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:45:29.552-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:45:29.551-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:45:29.553-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:45:29.552-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:45:29.553-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:45:29.565-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T19:46:26.811-0500] {processor.py:157} INFO - Started process (PID=63819) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:46:26.820-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:46:26.822-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:46:26.821-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:46:26.829-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:46:26.827-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:46:26.830-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:46:26.830-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:46:26.830-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:46:26.846-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:47:19.030-0500] {processor.py:157} INFO - Started process (PID=63879) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:47:19.038-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:47:19.040-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:47:19.039-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:47:19.046-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:47:19.045-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:47:19.047-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:47:19.046-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:47:19.047-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:47:19.058-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-07-28T19:48:12.957-0500] {processor.py:157} INFO - Started process (PID=63939) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:48:12.965-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:48:12.966-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:48:12.966-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:48:12.971-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:48:12.970-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:48:12.971-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:48:12.971-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:48:12.972-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:48:12.984-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2023-07-28T19:49:08.907-0500] {processor.py:157} INFO - Started process (PID=64001) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:49:08.915-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:49:08.916-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:49:08.916-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:49:08.923-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:49:08.921-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:49:08.923-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:49:08.923-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:49:08.923-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:49:08.939-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T19:50:03.300-0500] {processor.py:157} INFO - Started process (PID=64063) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:03.309-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:50:03.311-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:03.310-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:03.323-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:03.320-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:50:03.324-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:03.324-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:50:03.325-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:03.341-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-28T19:50:57.088-0500] {processor.py:157} INFO - Started process (PID=64124) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:57.096-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:50:57.098-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:57.097-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:57.106-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:57.103-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:50:57.106-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:50:57.106-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:50:57.107-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:50:57.122-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T19:51:56.903-0500] {processor.py:157} INFO - Started process (PID=64188) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:51:56.910-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:51:56.911-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:51:56.911-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:51:56.915-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:51:56.914-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:51:56.915-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:51:56.915-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:51:56.915-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:51:56.924-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T19:52:50.410-0500] {processor.py:157} INFO - Started process (PID=64251) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:52:50.418-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:52:50.419-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:52:50.419-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:52:50.424-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:52:50.423-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:52:50.424-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:52:50.424-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:52:50.425-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:52:50.436-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-07-28T19:53:42.838-0500] {processor.py:157} INFO - Started process (PID=64311) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:53:42.846-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:53:42.847-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:53:42.847-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:53:42.851-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:53:42.850-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:53:42.851-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:53:42.851-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:53:42.851-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:53:42.860-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T19:54:34.961-0500] {processor.py:157} INFO - Started process (PID=64370) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:54:34.969-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:54:34.969-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:54:34.969-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:54:34.973-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:54:34.972-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:54:34.973-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:54:34.973-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:54:34.974-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:54:34.983-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-07-28T19:55:33.481-0500] {processor.py:157} INFO - Started process (PID=64436) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:55:33.490-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:55:33.492-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:55:33.491-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:55:33.504-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:55:33.501-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:55:33.505-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:55:33.505-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:55:33.505-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:55:33.522-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T19:56:28.663-0500] {processor.py:157} INFO - Started process (PID=64498) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:56:28.672-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:56:28.675-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:56:28.673-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:56:28.686-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:56:28.683-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:56:28.687-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:56:28.687-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:56:28.688-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:56:28.708-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T19:57:20.311-0500] {processor.py:157} INFO - Started process (PID=64558) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:57:20.319-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:57:20.322-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:57:20.321-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:57:20.329-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:57:20.327-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:57:20.330-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:57:20.330-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:57:20.330-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:57:20.341-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T19:58:19.339-0500] {processor.py:157} INFO - Started process (PID=64622) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:58:19.346-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:58:19.348-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:58:19.347-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:58:19.352-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:58:19.351-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:58:19.353-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:58:19.353-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:58:19.353-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:58:19.365-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-07-28T19:59:19.613-0500] {processor.py:157} INFO - Started process (PID=64692) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:59:19.622-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T19:59:19.625-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:59:19.624-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:59:19.637-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:59:19.634-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T19:59:19.638-0500] {logging_mixin.py:150} INFO - [2023-07-28T19:59:19.638-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T19:59:19.639-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T19:59:19.657-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-07-28T20:00:11.663-0500] {processor.py:157} INFO - Started process (PID=64759) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:00:11.671-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:00:11.672-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:00:11.672-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:00:11.678-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:00:11.676-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:00:11.678-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:00:11.678-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:00:11.678-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:00:11.693-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T20:01:08.731-0500] {processor.py:157} INFO - Started process (PID=64822) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:01:08.746-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:01:08.748-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:01:08.747-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:01:08.756-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:01:08.754-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:01:08.756-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:01:08.756-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:01:08.757-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:01:08.774-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2023-07-28T20:02:10.586-0500] {processor.py:157} INFO - Started process (PID=64888) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:02:10.594-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:02:10.596-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:02:10.595-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:02:10.602-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:02:10.600-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:02:10.602-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:02:10.602-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:02:10.602-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:02:10.616-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T20:03:14.816-0500] {processor.py:157} INFO - Started process (PID=64962) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:03:14.825-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:03:14.828-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:03:14.826-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:03:14.839-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:03:14.836-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:03:14.840-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:03:14.840-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:03:14.840-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:03:14.856-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2023-07-28T20:04:16.305-0500] {processor.py:157} INFO - Started process (PID=65025) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:04:16.318-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:04:16.319-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:04:16.319-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:04:16.325-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:04:16.323-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:04:16.325-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:04:16.325-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:04:16.325-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:04:16.339-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-07-28T20:05:02.037-0500] {processor.py:157} INFO - Started process (PID=65078) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:05:02.045-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:05:02.046-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:05:02.046-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:05:02.050-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:05:02.049-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:05:02.050-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:05:02.050-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:05:02.050-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:05:02.060-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:06:04.689-0500] {processor.py:157} INFO - Started process (PID=65144) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:06:04.697-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:06:04.699-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:06:04.698-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:06:04.707-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:06:04.705-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:06:04.708-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:06:04.707-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:06:04.708-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:06:04.723-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T20:07:07.539-0500] {processor.py:157} INFO - Started process (PID=65209) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:07.553-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:07:07.555-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:07.554-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:07.567-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:07.564-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:07:07.568-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:07.567-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:07:07.568-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:07.587-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2023-07-28T20:07:56.276-0500] {processor.py:157} INFO - Started process (PID=65259) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:56.285-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:07:56.287-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:56.286-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:56.295-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:56.292-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:07:56.295-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:07:56.295-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:07:56.296-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:07:56.311-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-07-28T20:08:43.456-0500] {processor.py:157} INFO - Started process (PID=65309) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:08:43.463-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:08:43.464-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:08:43.464-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:08:43.468-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:08:43.467-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:08:43.468-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:08:43.468-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:08:43.468-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:08:43.477-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:09:51.152-0500] {processor.py:157} INFO - Started process (PID=65383) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:09:51.160-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:09:51.161-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:09:51.160-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:09:51.165-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:09:51.164-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:09:51.165-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:09:51.165-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:09:51.165-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:09:51.174-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2023-07-28T20:10:38.159-0500] {processor.py:157} INFO - Started process (PID=65432) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:10:38.168-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:10:38.170-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:10:38.169-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:10:38.182-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:10:38.178-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:10:38.182-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:10:38.182-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:10:38.183-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:10:38.202-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-07-28T20:11:37.061-0500] {processor.py:157} INFO - Started process (PID=65496) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:11:37.069-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:11:37.070-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:11:37.070-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:11:37.076-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:11:37.075-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:11:37.076-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:11:37.076-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:11:37.077-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:11:37.091-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-07-28T20:12:34.640-0500] {processor.py:157} INFO - Started process (PID=65560) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:12:34.648-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:12:34.650-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:12:34.650-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:12:34.658-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:12:34.656-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:12:34.659-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:12:34.658-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:12:34.659-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:12:34.674-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T20:13:29.257-0500] {processor.py:157} INFO - Started process (PID=65622) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:13:29.265-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:13:29.267-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:13:29.267-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:13:29.275-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:13:29.273-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:13:29.276-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:13:29.275-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:13:29.276-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:13:29.292-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T20:14:26.558-0500] {processor.py:157} INFO - Started process (PID=65684) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:14:26.567-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:14:26.570-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:14:26.569-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:14:26.581-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:14:26.578-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:14:26.582-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:14:26.581-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:14:26.582-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:14:26.596-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-07-28T20:15:20.770-0500] {processor.py:157} INFO - Started process (PID=65748) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:15:20.778-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:15:20.779-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:15:20.779-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:15:20.786-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:15:20.784-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:15:20.786-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:15:20.786-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:15:20.787-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:15:20.801-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-07-28T20:16:10.512-0500] {processor.py:157} INFO - Started process (PID=65806) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:16:10.521-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:16:10.523-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:16:10.522-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:16:10.535-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:16:10.532-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:16:10.535-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:16:10.535-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:16:10.536-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:16:10.556-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T20:17:07.044-0500] {processor.py:157} INFO - Started process (PID=65871) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:17:07.052-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:17:07.053-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:17:07.053-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:17:07.057-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:17:07.056-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:17:07.057-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:17:07.057-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:17:07.057-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:17:07.066-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:18:03.427-0500] {processor.py:157} INFO - Started process (PID=65934) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:03.435-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:18:03.436-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:03.435-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:03.440-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:03.439-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:18:03.440-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:03.440-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:18:03.441-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:03.451-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:18:51.543-0500] {processor.py:157} INFO - Started process (PID=65990) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:51.552-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:18:51.555-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:51.554-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:51.566-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:51.563-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:18:51.567-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:18:51.567-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:18:51.568-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:18:51.584-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T20:19:52.770-0500] {processor.py:157} INFO - Started process (PID=66060) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:19:52.777-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:19:52.778-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:19:52.778-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:19:52.782-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:19:52.781-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:19:52.782-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:19:52.782-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:19:52.783-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:19:52.793-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:20:47.784-0500] {processor.py:157} INFO - Started process (PID=66123) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:20:47.798-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:20:47.800-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:20:47.799-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:20:47.812-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:20:47.809-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:20:47.813-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:20:47.812-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:20:47.813-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:20:47.833-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2023-07-28T20:21:35.436-0500] {processor.py:157} INFO - Started process (PID=66179) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:21:35.443-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:21:35.444-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:21:35.444-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:21:35.448-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:21:35.447-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:21:35.448-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:21:35.448-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:21:35.449-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:21:35.459-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:22:28.500-0500] {processor.py:157} INFO - Started process (PID=66239) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:22:28.509-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:22:28.512-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:22:28.510-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:22:28.523-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:22:28.520-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:22:28.524-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:22:28.523-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:22:28.524-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:22:28.543-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2023-07-28T20:23:22.164-0500] {processor.py:157} INFO - Started process (PID=66299) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:23:22.174-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:23:22.175-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:23:22.174-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:23:22.179-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:23:22.177-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:23:22.179-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:23:22.179-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:23:22.179-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:23:22.188-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-28T20:24:23.117-0500] {processor.py:157} INFO - Started process (PID=66365) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:24:23.126-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:24:23.127-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:24:23.127-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:24:23.135-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:24:23.133-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:24:23.136-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:24:23.135-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:24:23.136-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:24:23.152-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-07-28T20:25:14.535-0500] {processor.py:157} INFO - Started process (PID=66427) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:25:14.543-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:25:14.544-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:25:14.544-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:25:14.548-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:25:14.547-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:25:14.548-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:25:14.548-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:25:14.548-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:25:14.558-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-07-28T20:26:06.702-0500] {processor.py:157} INFO - Started process (PID=66488) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:06.710-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:26:06.712-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:06.712-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:06.720-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:06.718-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:26:06.721-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:06.720-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:26:06.721-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:06.738-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-07-28T20:26:57.383-0500] {processor.py:157} INFO - Started process (PID=66547) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:57.391-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:26:57.392-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:57.391-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:57.395-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:57.394-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:26:57.396-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:26:57.396-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:26:57.396-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:26:57.406-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-28T20:27:48.591-0500] {processor.py:157} INFO - Started process (PID=66690) to work on /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:27:48.599-0500] {processor.py:826} INFO - Processing file /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-28T20:27:48.600-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:27:48.600-0500] {dagbag.py:541} INFO - Filling up the DagBag from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:27:48.605-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:27:48.604-0500] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-28T20:27:48.606-0500] {logging_mixin.py:150} INFO - [2023-07-28T20:27:48.606-0500] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-28T20:27:48.606-0500] {processor.py:838} WARNING - No viable dags retrieved from /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-28T20:27:48.619-0500] {processor.py:179} INFO - Processing /home/joha/anaconda3/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
